config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root 'home#top'
  get 'static_pages/terms'
  get 'static_pages/privacy_policy'

  namespace :users do
    get 'profile'
    patch 'profile_update'
  end
  resources :users, only: [:show]

  resources :fields, only: [:show] do
    get 'search', on: :collection
  end
  resources :bookmarks, only: [:create, :destroy]
  resources :reviews
  resources :contacts, only: [:new]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  GUEST_EMAIL = 'guest@example.com'.freeze
  GUEST_NAME = "ゲストユーザー".freeze

  has_many :reviews, dependent: :destroy
  has_many :fields, through: :reviews
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_fields, through: :bookmarks, source: :field
  before_save { email.downcase! }
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  # VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[\d])\w{6,12}\z/
  # validates :password, format: { with: VALID_PASSWORD_REGEX, message: "は半角6~12文字・英大文字・小文字・数字それぞれ１文字以上含む必要があります" }
  validate :validate_icon_img
  paginates_per 9
  has_one_attached :icon_img
  attribute :new_icon_img
  before_validation :assign_new_icon_img

  def validate_icon_img
    return unless icon_img.attached?
    return if image?

    errors.add(:icon_img, "は画像データではありません。")
  end

  def image?
    return false unless icon_img.attached?

    %w(image/jpg image/jpeg image/png image/gif).include?(icon_img.blob.content_type)
  end

  def self.guest
    find_or_create_by!(email: GUEST_EMAIL) do |user|
      user.name = GUEST_NAME
      user.password = SecureRandom.urlsafe_base64
    end
  end

  private

  def assign_new_icon_img
    return if new_icon_img.blank?

    self.icon_img = new_icon_img
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーさんのパスワードは再設定できません。'
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: [:update, :destroy]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーさんは、データの編集・削除などができない設定になっています。'
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーさん、ようこそ TO_CAMP へ！気になるキャンプ場を探してみましょう。'
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @fields = @user.bookmark_fields.includes(:reviews).page(params[:page])
  end

  def profile
  end

  def profile_update
    if current_user.email != User::GUEST_EMAIL
      @user = current_user
      if @user.update(user_params)
        redirect_to users_profile_path, notice: "プロフィールを更新しました"
      else
        flash.now[:alert] = "プロフィールを更新できませんでした"
        render :profile
      end
    else
      redirect_to root_path, alert: "#{User::GUEST_NAME}さんは、データの編集・削除などができない設定になっています。"
    end
  end

  private

  def user_params
    params.require(:user).permit(:new_icon_img, :name, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/profile.html.erb
<% provide(:title, "アイコン・ネーム編集") %>
  <% if flash[:notice] %>
    <%= render 'layouts/flash_messages' %>
  <% end %>
  <% if flash[:alert] %>
    <%= render 'layouts/flash_messages' %>
  <% end %>
<div class="d-flex align-items-center flex-column mt-5">
  <h2>
    <span class="page-title">I</span>
    <span class="page-title">C</span>
    <span class="page-title">O</span>
    <span class="page-title">N</span>
    <span class="page-title">-</span>
    <span class="page-title">N</span>
    <span class="page-title">A</span>
    <span class="page-title">M</span>
    <span class="page-title">E</span>
  </h2>
  <p class="camp-search text-center">アイコン・ネーム編集</p>
</div>
<div class="container">
  <div class="col-md-8 text-center offset-md-2 col-sm-12 shadow rounded my-5">
    <div class="col-md-10 offset-md-1 col-sm-12 col-xs-12 pt-5">
      <%= form_with model: @user, url: users_profile_update_path, local: true, method: :patch do |f| %>
        <%= hidden_field_tag :id, @user.id %>
        <div class="border-bottom my-3 pb-3">
          <% if current_user.icon_img.attached? %>
            <%= image_tag current_user.icon_img, class: "rounded-circle", size: "65x65" %>
          <% else %>
            <i class="fas fa-user-plus fa-4x ms-4"></i>
          <% end %>
        </div>
        <div class="form-group form-row border-bottom">
          <div class="my-3">
            <%= f.label :new_icon_img, "アイコン画像" %>
          </div>
          <%= f.file_field :new_icon_img, autocomplete: "name" %>
        </div>
        <div class="form-group form-row border-bottom m-3">
          <%= f.text_field :name, autocomplete: "name", class: "form-control col-10 px-2", placeholder: "" %>
        </div>
        <div class="pb-3">
          <%= f.submit "更新", class: "green-btn btn rounded-pill w-50 m-auto my-4" %>
        </div>
        <div class="pb-3">
          <%= link_to "トップページに戻る", root_path, class: "white-btn btn rounded-pill w-50 mb-5" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "気になるキャンプ場") %>
<div class="container">
  <%= render "shared/fields_count", fields: @fields %>
  <div class="d-flex align-items-center flex-column mt-5">
    <h2>
      <span class="page-title">B</span>
      <span class="page-title">O</span>
      <span class="page-title">O</span>
      <span class="page-title">K</span>
      <span class="page-title">-</span>
      <span class="page-title">M</span>
      <span class="page-title">A</span>
      <span class="page-title">R</span>
      <span class="page-title">K</span>
    </h2>
    <h3 class="camp-search text-center"><%= "気になるキャンプ場：#{@fields.total_count}件" %></h3>
  </div>
  <div class="row">
    <% if Bookmark.find_by(params[:id]).present? %>
      <%= render "shared/search_bookmark", fields: @fields %>
    <% else %>
      <p>気になるキャンプ場やお気に入りのキャンプ場をブックマークしてみよう！<br>キャンプ場詳細ページの <i class="far fa-bookmark"></i> このマークを押すと登録完了！</p>
    <% end %>
  </div>
  <%= paginate @fields %>
  <div class="text-center">
    <%= link_to "トップページに戻る", root_path, class: "white-btn btn rounded-pill w-50 m-auto my-5" %>
  </div>
</div>