config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root 'home#top'
  get 'static_pages/terms'
  get 'static_pages/privacy_policy'

  namespace :users do
    get 'profile'
    patch 'profile_update'
  end
  resources :users, only: [:show]

  resources :fields, only: [:show] do
    get 'search', on: :collection
  end
  resources :bookmarks, only: [:create, :destroy]
  resources :reviews
  resources :contacts, only: [:new]
end

app/views/shared/_article.html.erb
<article>
  <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag "top-img.jpg", class: "lazyload d-block w-100", alt: "キャンプ場風景写真" %>
      </div>
      <div class="carousel-item">
        <%= image_tag "top-img2.jpg", class: "lazyload d-block w-100", alt: "焚き火の写真" %>
      </div>
      <div class="carousel-item">
        <%= image_tag "top-img3.jpg", class: "lazyload d-block w-100", alt: "テントの写真" %>
      </div>
    </div>
  </div>
  <div class="article-card col-lg-8 text-center">
    <p class="mb-0 pt-3">
      <span class="m-2">次はどこでキャンプしようか</span>
    </p>
    <h1 class="site-title">
      <span class="m-5">TO_CAMP</span>
    </h1>
  </div>
</article>

app/views/shared/_fields_count.html.erb
<p class="search-number">
  <% if fields.present? %>
    <%= fields_current_number(fields.current_page,fields.size) %>件を表示 / 全<%= fields.total_count %>件
  <% else %>
    0件を表示 / 全<%= fields.total_count %>件
  <% end %>
</p>

app/views/shared/_footer.html.erb
<% if current_user.blank? %>
  <div class="d-flex align-items-center justify-content-end my-4 me-1">
    <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class: "btn btn-outline-light me-3" %>
    <%= link_to "ログイン", "/users/sign_in", class: "btn btn-outline-light me-3" %>
    <%= link_to "新規登録", "/users/sign_up", class: "create-btn btn btn-light me-3" %>
  </div>
<% else %>
  <div class="d-flex align-items-center justify-content-end">
    <div class="nav-item d-sm-inline-block me-3 text-white">
      <%= current_user.name %>
    </div>
    <div class="btn-group dropup me-2">
      <div class="btn rounded-circle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-offset="0,5">
        <% if current_user.icon_img.attached? %>
          <%= image_tag current_user.icon_img, class: "icon_img rounded-circle" %>
        <% else %>
          <i class="fas fa-user-plus fa-4x ms-3"></i>
        <% end %>
      </div>
      <ul class="dropdown-menu dropdown-footer rounded shadow">
        <li><%= link_to "アイコン・ネーム編集", "/users/profile", class: "dropdown-item text-white" %></li>
        <li><%= link_to "メール・パスワード編集", "/users/edit", class: "dropdown-item text-white" %></li>
        <li><%= link_to "気になるキャンプ場リスト", user_path(user), class: "dropdown-item text-white" %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, class: "dropdown-item text-white", method: :delete %></li>
      </ul>
    </div>
  </div>
<% end %>
<ul>
  <li><%= link_to "お問い合わせ(キャンプ場追加希望もこちら)", new_contact_path, class: "footer-link text-white" %></li>
  <li><%= link_to "利用規約", static_pages_terms_path, class: "footer-link text-white" %></li>
  <li><%= link_to "プライバシーポリシー", static_pages_privacy_policy_path, class: "footer-link text-white" %></li>
</ul>
<div class="text-center mb-3 text-white">
  ©2021 TO_CAMP All Rights Reserved.
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-light">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <h1 class="site-title">TO_CAMP</h1>
    <% end %>
    <div class="d-flex">
      <i class="fas fa-search ms-2" style=" margin-top: 12px; position:absolute;"></i>
      <%= search_form_for q, url: search_fields_path do |f| %>
        <%= f.search_field :name_cont, required: true, class: "form-control px-4", placeholder: ' キャンプ場名を入力' %>
        <% f.submit %>
      <% end %>
    </div>
  </div>
</nav>
<% if current_user.blank? %>
  <div class="d-flex align-items-center justify-content-end my-4 me-1">
    <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class: "btn btn-outline-secondary me-3" %>
    <%= link_to "ログイン", "/users/sign_in", class: "btn btn-outline-secondary me-3" %>
    <%= link_to "新規登録", "/users/sign_up", class: "secondary-btn btn btn-secondary me-3" %>
  </div>
<% else %>
  <div class="d-flex align-items-center justify-content-end">
    <div class="nav-item d-sm-inline-block me-3 text-secondary">
      <%= current_user.name %>
    </div>
    <div class="btn-group dropdown me-2">
      <div class="btn rounded-circle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-offset="0,5">
        <% if current_user.icon_img.attached? %>
          <%= image_tag current_user.icon_img, class: "icon_img rounded-circle" %>
        <% else %>
          <i class="fas fa-user-plus fa-4x ms-3 text-secondary"></i>
        <% end %>
      </div>
      <ul class="dropdown-menu rounded shadow d-header-bg">
        <li><%= link_to "アイコン・ネーム編集", "/users/profile", class: "dropdown-item text-secondary" %></li>
        <li><%= link_to "メール・パスワード編集", "/users/edit", class: "dropdown-item text-secondary" %></li>
        <li><%= link_to "気になるキャンプ場リスト", user_path(user), class: "dropdown-item text-secondary" %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, class: "dropdown-item text-secondary", method: :delete %></li>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_scroll_btn.html.erb
<span id="back" style="display: none;">
  <a href="">
    <%= image_tag asset_path('scroll_btn.jpg'), data: {"turbolinks"=>false}, class: "arrow rounded-circle" %>
  </a>
</span>

app/views/shared/_search_bookmark.html.erb
<% fields.each do |field| %>
  <div class="col-sm-12 col-md-6 col-lg-6 col-xl-4">
    <div class="card shadow bg-white rounded my-5">
      <% if field.image.blank? %>
        <%= image_tag "no-image.jpg", width: "100%", height: "100%", alt: "草原の写真" %>
      <% else %>
        <%= image_tag field.image.variant(gravity: :center, resize:'500x500^', crop:"500x500+0+0").processed, width: "100%", height: "100%", alt: "キャンプ場の写真" %>
      <% end %>
      <div class="card-body">
        <h5 class="card-title">
          <%= link_to field.name, field_path(field) %>
        </h5>
        <div class="rating d-flex align-items-center m-2">
          <%= image_tag "star-on.png",class: "me-2" %><%= rating(field.reviews) %>
        </div>
        <div class="mb-1">
          <i class="fas fa-map-marker-alt fa-fw"></i>
          <cite title="<%= field.address %>">
          <%= field.address %>
        </div>
        <div class="mb-1">
          <i class="fas fa-mobile-alt fa-fw"></i>
          <% if field.phone_number.present? %>
            <a href="tel:<%= field.phone_number %>"><%= field.phone_number %></a>
          <% else %>
            -
          <% end %>
        </div>
        <div class="mb-1">
          <i class="fas fa-clock fa-fw"></i>
          チェックイン：<%= field.check_in %><br>
          <i class="fas fa-clock fa-fw"></i>
          チェックアウト：<%= field.check_out %>
        </div>
        <div class="mb-1">
          <i class="fas fa-campground fa-fw"></i>
          デイキャンプ：<%= field.day_camp_description %>
        </div>
        <div class="mb-1">
          <i class="fas fa-map-marked-alt fa-fw"></i> 立地：
          <% if field.sea %>
            <i class="fas fa-umbrella-beach fa-fw"></i>海
          <% end %>
          <% if field.lake %>
            <i class="far fa-circle fa-fw"></i>湖
          <% end %>
          <% if field.river %>
            <i class="fas fa-water fa-fw"></i>川
          <% end %>
          <% if field.mountain %>
            <i class="fas fa-mountain fa-fw"></i> 山
          <% end %>
          <% if field.woods %>
            <i class="fas fa-tree fa-fw"></i>林間
          <% end %>
        </div>
        <div class="mb-1">
          <i class="fas fa-mountain fa-fw"></i>
          標高：<%= field.elevation %> m
        </div>
        <div class="mb-1">
          <i class="fas fa-th-large fa-fw"></i>
          <% if field.section_site %>
            区画サイト：<%= field.section_site_price %>/<%= field.section_site_size %>
          <% else %>
            区画サイト：無
          <% end %>
        </div>
        <div class="mb-1">
          <i class="far fa-square fa-fw"></i>
          <% if field.section_site %>
            フリーサイト：<%= field.free_site_price %>/<%= field.free_site_size %>
          <% else %>
            フリーサイト：無
          <% end %>
        </div>
        <div class="mb-1">
          <i class="fas fa-chess-board fa-fw"></i> サイトの地面：
          <% if field.ground_turf %>
            芝
          <% end %>
          <% if field.ground_soil %>
            土
          <% end %>
          <% if field.ground_wood_deck %>
            ウッドデッキ
          <% end %>
          <% if field.ground_sand %>
            砂
          <% end %>
        </div>
        <div class="mb-1">
          <i class="fas fa-fire-alt fa-fw"></i>
          <% if field.bonfire %>
            焚き火：可
          <% else %>
            焚き火：禁止
          <% end %>
        </div>
        <div class="mb-1">
          <i class="fas fa-burn fa-fw"></i>
          <% if field.direct_fire %>
            直火：可
          <% else %>
            直火：禁止
          <% end %>
        </div>
        <div class="mb-1">
          <i class="fas fa-car fa-fw"></i>
          車の横付け：
          <% if field.car %>
            可
          <% else %>
            不可
          <% end %>
        </div>
        <div class="mb-1">
          <i class="fas fa-paw fa-fw"></i>
          ペット：
          <% if field.pets %>
            可
          <% else %>
            不可
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_show_count.html.erb
<p class="search-number">
  <% if fields.present? %>
    <%= show_current_number(fields.current_page,fields.size) %>件を表示 / 全<%= fields.total_count %>件
  <% else %>
    0件を表示 / 全<%= fields.total_count %>件
  <% end %>
</p>