config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root 'home#top'
  get 'static_pages/terms'
  get 'static_pages/privacy_policy'

  namespace :users do
    get 'profile'
    patch 'profile_update'
  end
  resources :users, only: [:show]

  resources :fields, only: [:show] do
    get 'search', on: :collection
  end
  resources :bookmarks, only: [:create, :destroy]
  resources :reviews
  resources :contacts, only: [:new]
end

app/models/field.rb
class Field < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :users, through: :reviews
  has_many :bookmarks, dependent: :destroy
  paginates_per 9
  validates :name, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 100 }
  validates :place_id, uniqueness: true
  has_one_attached :image
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  def show
    @field = Field.find(params[:id])
    @reviews = @field.reviews.includes(:user).page(params[:page])
  end

  def search
    @fields = @q.result.page(params[:page])
  end
end

app/helpers/fields_helper.rb
module FieldsHelper
  def rating(reviews)
    normalized_reviews = Array(reviews).compact
    return 0.0 if normalized_reviews.empty?

    rate_sum = normalized_reviews.sum do |review|
      review.respond_to?(:rate) ? review.rate.to_f : review.to_f
    end
    (rate_sum / normalized_reviews.count).round(2)
  end

  def fields_current_number(current_page, size)
    current_page = current_page.to_i
    size = size.to_i

    if size > 8
      last = size * current_page
      first = last - 8
      "#{first} ~ #{last}"
    else
      "1 ~ #{size}"
    end
  end
end

app/views/fields/_bookmark.html.erb
<%= link_to bookmarks_path(:field_id => @field.id), method: :post, remote: true do %>
  <i class="far fa-bookmark"></i>
<% end %>

app/views/fields/_bookmark_tag.html.erb
<div id="bookmark_tag">
  <% if Bookmark.find_by(user_id: current_user.id, field_id: field.id) %>
    <%= render "unbookmark", field: @field %>
  <% else %>
    <%= render "bookmark",field: @field %>
  <% end %>
</div>

app/views/fields/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(field_id: @field.id), :field_id => @field.id), method: :delete, remote: true do %>
  <i class="fas fa-bookmark"></i>
  <small><%= flash[:success] = "気になるキャンプ場△" %></small>
<% end %>

app/views/fields/search.html.erb
<% provide(:title, "検索結果") %>
<div class="container">
  <%= render "shared/fields_count", fields: @fields %>
  <div class="row m-0">
    <div class="d-flex align-items-center flex-column my-5">
      <h2>
        <span class="page-title">S</span>
        <span class="page-title">E</span>
        <span class="page-title">A</span>
        <span class="page-title">R</span>
        <span class="page-title">C</span>
        <span class="page-title">H</span>
        <span class="page-title">-</span>
        <span class="page-title">R</span>
        <span class="page-title">E</span>
        <span class="page-title">S</span>
        <span class="page-title">U</span>
        <span class="page-title">L</span>
        <span class="page-title">T</span>
        <span class="page-title">S</span>
      </h2>
      <h3 class="camp-search text-center"><%= "検索結果：#{@fields.total_count}件" %></h3>
    </div>
  </div>
  <thead>
    <tr>
      <th><%= sort_link(@q, :elevation, "標高順に並べ替える") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <div class="row">
    <% if @fields.length != 0 %>
      <%= render "shared/search_bookmark", fields: @fields %>
    <% else %>
      <div class="text-center">
        キャンプ場は見つかりませんでした
      </div>
    <% end %>
  </div>
  <div class="text-center">
    <%= link_to "トップページに戻る", root_path, class: "white-btn btn rounded-pill w-50 m-auto my-5" %>
  </div>
</div>
<%= paginate @fields %>